more tests

diff --git a/syzzle-test b/syzzle-test
--- a/syzzle-test
+++ b/syzzle-test
@@ -13,7 +13,7 @@ fi
 # Setup
 
 basedir=""
-trap 'rc="$?" ; set +ex ; if [ $rc = 0 ]; then echo "TESTS PASSED"; else echo "TESTS FAILED ($rc)"; fi ; [ "$basedir" ] && rm -rf "$basedir" ; exit $rc' EXIT
+trap 'rc="$?" ; set +ex ; if [ $rc = 0 ]; then echo "ALL TESTS PASSED"; else echo "TEST FAILED ($rc)"; fi ; [ "$basedir" ] && rm -rf "$basedir" ; exit $rc' EXIT
 basedir="$(mktemp -d)"
 
 mkdir -p "$basedir/sw/"{abc,def,ghi,jkl}/{1.0,1.1,1.2,1.3}/{bin,lib}
@@ -21,33 +21,139 @@ export SYZ_PATH="$basedir/sw"
 
 
 function run {
-	echo "+ $*"
+	echo "+ ${FUNCNAME[0]} $*"
 	o="$("$@")"
+	rc="$?"
 }
 
-function check_output {
+function run_tty {
+	echo "+ ${FUNCNAME[0]} $*"
+	function tty {
+		:
+	}
+	o="$("$@")"
+	rc="$?"
+	unset -f tty
+}
+
+
+function check {
+	local what="$1" ; shift
+	set -e
+	check_"$what" "$@"
+	set +e
+}
+
+function check_success {
+	echo "++ ${FUNCNAME[0]}"
+	[ "$rc" = "0" ]
+}
+
+function check_failure {
+	local code="$1" ; shift
+	echo "++ ${FUNCNAME[0]} $code"
+	if [ "$code" ]; then
+		[ "$rc" = "$code" ]
+	else
+		[ "$rc" != "0" ]
+	fi
+}
+
+function check_output_pattern {
 	local i
 	for i; do
-		echo "++ check_output $i" 
+		echo "++ ${FUNCNAME[0]} $i"
 		grep -q "$i" <<<"$o"
 	done
 }
 
-function check_env {
+function check_output_exact {
+	local target="$1" ; shift
+	echo "++ ${FUNCNAME[0]}"
+	[ "$o" = "$target" ]
+}
+
+function check_envvar_pattern {
 	local var="$1" ; shift
 	local pattern="$1" ; shift
 	local -n value="$var"
-	echo "++ check_env $var $pattern" 
+	echo "++ ${FUNCNAME[0]} $var $pattern"
 	grep -q "$pattern" <<<"$value"
 }
 
+function check_envvar_exact {
+	local var="$1" ; shift
+	local target="$1" ; shift
+	local -n value="$var"
+	echo "++ ${FUNCNAME[0]} $var"
+	[ "$value" = "$target" ]
+}
+
+function check_envvar_set {
+	local i
+	for i; do
+		echo "++ ${FUNCNAME[0]} $i"
+		[ "${!i+set}" = "set" ]
+	done
+}
+
+function check_envvar_unset {
+	local i
+	for i; do
+		echo "++ ${FUNCNAME[0]} $i"
+		[ "${!i+set}" != "set" ]
+	done
+}
+
+echo "+ prelim"
+check envvar_pattern "SYZ_PATH" '^'"$basedir"'/sw$'
+check envvar_unset SYZ_{MODULES,MODULES_ABS,INACTIVE_MODULES}
 
 set -e
-
 . ./syzzle
+set +e
 
-check_env "SYZ_VERSION" "."
+check envvar_pattern "SYZ_VERSION" '.'
+check envvar_pattern "SYZ_PATH" '^'"$basedir"'/sw$'
+check envvar_set SYZ_{MODULES,MODULES_ABS,INACTIVE_MODULES}
+check envvar_exact "SYZ_MODULES" ''
+check envvar_exact "SYZ_MODULES_ABS" ''
+check envvar_exact "SYZ_INACTIVE_MODULES" ''
 
 run syz version
-check_output "version" "$SYZ_VERSION"
+check success
+check output_pattern "version" "$SYZ_VERSION"
+
+run syz loaded
+check success
+check output_exact ""
+run_tty syz loaded
+check success
+check output_pattern 'No modules currently loaded\.'
+
+run syz inactive
+check success
+check output_exact ""
+run_tty syz inactive
+check success
+check output_pattern 'No inactive modules\.'
+
+run syz empty
+check success
+o_empty="$o"
+run syz
+check success
+check output_exact "$o_empty"
+
+run syz show
+check success
+o_show="$o"
+run syz status
+check success
+check output_exact "$o_show"
+
+
+
+
+
 
