add -q (quiet) flag to syzzle-test (will be good for a git pre-commit hook)

diff --git a/syzzle-test b/syzzle-test
--- a/syzzle-test
+++ b/syzzle-test
@@ -16,6 +16,10 @@ for i; do
 		-v)
 			verbose=y
 			;;
+		-q)
+			echo "Running tests..."
+			quiet=y
+			;;
 	esac
 done
 unset i
@@ -23,7 +27,7 @@ unset i
 # Setup
 
 basedir=""
-trap '__syz_rc="$?" ; set +ex ; echo ; if [ $__syz_rc = 0 ]; then echo "ALL TESTS PASSED"; else echo "TEST FAILED ($__syz_rc)"; fi ; [ "$basedir" ] && rm -rf "$basedir" ; exit $__syz_rc' EXIT
+trap '__syz_rc="$?" ; set +ex ; blankline ; if [ $__syz_rc = 0 ]; then echo "ALL TESTS PASSED"; else echo "TEST FAILED ($__syz_rc)"; fi ; [ "$basedir" ] && rm -rf "$basedir" ; exit $__syz_rc' EXIT
 basedir="${SYZZLE_TEST_BASEDIR:-$(mktemp -d)}"
 if [ ! -e "$basedir" ]; then
 	mkdir -p "$basedir"
@@ -51,9 +55,23 @@ function unindent {
 	__syz_marker="${__syz_marker%+}"
 }
 
-function msg {
-	echo "$__syz_marker $*"
-}
+if [ "$quiet" = y ]; then
+	function blankline {
+		:
+	}
+
+	function msg {
+		:
+	}
+else
+	function blankline {
+		echo
+	}
+
+	function msg {
+		echo "$__syz_marker $*"
+	}
+fi
 
 function do_run {
 	indent
@@ -293,7 +311,7 @@ check envvar_unset SYZ_{MODULES,MODULES_ABS,INACTIVE_MODULES}
 check no_leaked_vars --setup
 check no_leaked_aliases --setup
 
-echo
+blankline
 msg "load"
 set -e
 . ./syzzle
@@ -309,7 +327,7 @@ check envvar_exact "SYZ_MODULES" ''
 check envvar_exact "SYZ_MODULES_ABS" ''
 check envvar_exact "SYZ_INACTIVE_MODULES" ''
 
-echo
+blankline
 run syz avail
 check success
 check output_exact ''
@@ -323,7 +341,7 @@ done
 unset i
 # FIXME: current and default symlinks
 
-echo
+blankline
 run syz avail
 check success
 check output_exact "$test_pvs"
@@ -332,12 +350,12 @@ check success
 check output_pattern 'Available modules'
 check output_pattern $test_pvs
 
-echo
+blankline
 run syz version
 check success
 check output_pattern "version" "$SYZ_VERSION"
 
-echo
+blankline
 run syz empty
 check success
 __syz_o_empty="$__syz_o"
@@ -348,19 +366,19 @@ run syz status
 check success
 check output_exact "$__syz_o_empty"
 
-echo
+blankline
 run syz show
 check success
 __syz_o_show="$__syz_o"
 
-echo
+blankline
 check modules_not_loaded 'abc/1.0'
 check modules_not_loaded 'def/1.1'
 check modules_not_loaded 'ghi/1.2'
 check no_modules_loaded
 check no_modules_inactive
 
-echo
+blankline
 run syz load abc/1.0
 check success
 check output_pattern 'Loading' 'abc/1.0'
@@ -376,7 +394,7 @@ check modules_not_loaded 'def/1.1'
 check modules_not_loaded 'ghi/1.2'
 check no_modules_inactive
 
-echo
+blankline
 run syz load def/1.1
 check success
 check output_pattern 'Loading' 'def/1.1'
@@ -392,7 +410,7 @@ check modules_loaded 'def/1.1'
 check modules_not_loaded 'ghi/1.2'
 check no_modules_inactive
 
-echo
+blankline
 run syz load ghi/1.2
 check success
 check output_pattern 'Loading' 'ghi/1.2'
@@ -408,7 +426,7 @@ check modules_loaded 'def/1.1'
 check modules_loaded 'ghi/1.2'
 check no_modules_inactive
 
-echo
+blankline
 run syz unload def/1.1
 check success
 check output_pattern 'Unloading' 'def/1.1'
@@ -424,7 +442,7 @@ check modules_not_loaded 'def/1.1'
 check modules_loaded 'ghi/1.2'
 check no_modules_inactive
 
-echo
+blankline
 run syz unload abc/1.0
 check success
 check output_pattern 'Unloading' 'abc/1.0'
@@ -440,7 +458,7 @@ check modules_not_loaded 'def/1.1'
 check modules_loaded 'ghi/1.2'
 check no_modules_inactive
 
-echo
+blankline
 run syz load def/1.1
 check success
 check output_pattern 'Loading' 'def/1.1'
@@ -456,7 +474,7 @@ check modules_loaded 'def/1.1'
 check modules_loaded 'ghi/1.2'
 check no_modules_inactive
 
-echo
+blankline
 run syz unload ghi/1.2
 check success
 check output_pattern 'Unloading' 'ghi/1.2'
@@ -472,7 +490,7 @@ check modules_loaded 'def/1.1'
 check modules_not_loaded 'ghi/1.2'
 check no_modules_inactive
 
-echo
+blankline
 run syz unload def/1.1
 check success
 check output_pattern 'Unloading' 'def/1.1'
@@ -489,7 +507,7 @@ check modules_not_loaded 'ghi/1.2'
 check no_modules_loaded
 check no_modules_inactive
 
-echo
+blankline
 run syz load ghi/1.2
 check success
 check output_pattern 'Loading' 'ghi/1.2'
@@ -505,7 +523,7 @@ check modules_not_loaded 'def/1.1'
 check modules_loaded 'ghi/1.2'
 check no_modules_inactive
 
-echo
+blankline
 run syz load ghi/1.2
 check success
 check output_pattern 'Module ghi/1.2 is already loaded, skipping'
@@ -522,7 +540,7 @@ check modules_loaded 'ghi/1.2'
 check no_modules_inactive
 
 # loading multiple modules on one cmdline
-echo
+blankline
 run syz load {abc/1.0,def/1.1}
 check success
 check output_pattern 'Loading' {abc/1.0,def/1.1}
@@ -539,7 +557,7 @@ check modules_loaded 'ghi/1.2'
 check no_modules_inactive
 
 # unloading multiple modules on one cmdline
-echo
+blankline
 run syz unload {abc/1.0,def/1.1,ghi/1.2}
 check success
 check output_pattern 'Unloading' {abc/1.0,def/1.1,ghi/1.2}
@@ -557,7 +575,7 @@ check no_modules_loaded
 check no_modules_inactive
 
 # trying to load module with unknown package name
-echo
+blankline
 run syz load xyz/0.9
 check failure
 check output_pattern 'No such module: xyz/0.9'
@@ -576,7 +594,7 @@ check no_modules_loaded
 check no_modules_inactive
 
 # trying to load module with unknown package name
-echo
+blankline
 run syz load xyz
 check failure
 check output_pattern 'No such module: xyz'
@@ -595,7 +613,7 @@ check no_modules_loaded
 check no_modules_inactive
 
 # trying to load module with unknown version
-echo
+blankline
 run syz load abc/0.9
 check failure
 check output_pattern 'No such module: abc/0.9'
@@ -614,7 +632,7 @@ check no_modules_loaded
 check no_modules_inactive
 
 # unload module which is known but not loaded
-echo
+blankline
 run syz unload abc/1.0
 check success
 check output_pattern 'Error: No module named abc/1.0 is loaded'
@@ -632,7 +650,7 @@ check no_modules_loaded
 check no_modules_inactive
 
 # unload module with unknown package name
-echo
+blankline
 run syz unload xyz/0.9
 check success
 check output_pattern 'Error: No module named xyz/0.9 is loaded'
@@ -651,7 +669,7 @@ check no_modules_loaded
 check no_modules_inactive
 
 # unload module with unknown package name
-echo
+blankline
 run syz unload xyz
 check success
 check output_pattern 'Error: No module named xyz is loaded'
@@ -670,7 +688,7 @@ check no_modules_loaded
 check no_modules_inactive
 
 # unload module with unknown version
-echo
+blankline
 run syz unload abc/0.9
 check success
 check output_pattern 'Error: No module named abc/0.9 is loaded'
