__syz::foobar -> __syz::__foobar (for readability)

diff --git a/syzzle b/syzzle
--- a/syzzle
+++ b/syzzle
@@ -22,7 +22,7 @@ SYZ_VERSION=0.0.1
 
 
 function syz {
-	if ! __syz::rerun_if_updated "$@"; then
+	if ! __syz::__rerun_if_updated "$@"; then
 		syz::dispatch "$@"
 	fi
 }
@@ -82,21 +82,21 @@ function syz::status {
 
 function syz::loaded {
 	# FIXME: identify orphaned modules and display them differently/separately.
-	# Oprhaned modules are those that have been loaded, but now fail __syz::is_loadable_dir.
+	# Oprhaned modules are those that have been loaded, but now fail __syz::__is_loadable_dir.
 	local -a _loaded
-	__syz::parse_list _loaded "$SYZ_MODULES"
+	__syz::__parse_list _loaded "$SYZ_MODULES"
 	local _loaded_str
-	__syz::stringify_array -d "$__syz_nl" _loaded_str _loaded
-	__syz::columnate "Currently loaded modules" "No modules currently loaded." <<< "$_loaded_str"
+	__syz::__stringify_array -d "$__syz_nl" _loaded_str _loaded
+	__syz::__columnate "Currently loaded modules" "No modules currently loaded." <<< "$_loaded_str"
 }
 
 
 function syz::inactive {
 	local -a _loaded
-	__syz::parse_list _loaded "$SYZ_INACTIVE_MODULES"
+	__syz::__parse_list _loaded "$SYZ_INACTIVE_MODULES"
 	local _loaded_str
-	__syz::stringify_array -d "$__syz_nl" _loaded_str _loaded
-	__syz::columnate "Inactive modules" "No inactive modules." <<< "$_loaded_str"
+	__syz::__stringify_array -d "$__syz_nl" _loaded_str _loaded
+	__syz::__columnate "Inactive modules" "No inactive modules." <<< "$_loaded_str"
 }
 
 
@@ -107,14 +107,14 @@ function syz::load {
 	local _resolved_pv _resolved_dir
 	for i; do
 		# FIXME: strip any trailing "/*" when doing this check
-		if __syz::isloaded "$i" _actually_loaded; then
+		if __syz::__isloaded "$i" _actually_loaded; then
 			# FIXME: maybe force reload (ie. unload then reload) it in this case?
 			# FIXME: if already loaded, swap versions (ie. unload first)
 			echo "Module $_actually_loaded is already loaded, skipping"
 			continue
 		fi
 
-		if __syz::resolve_loadable_dir "$i" _resolved_pv _resolved_dir; then
+		if __syz::__resolve_loadable_dir "$i" _resolved_pv _resolved_dir; then
 			echo "Loading $_resolved_pv from $_resolved_dir"
 			# actually load it
 			# FIXME: this should be a function
@@ -123,7 +123,7 @@ function syz::load {
 			local subdir
 			for subdir in "${__syz_subdirs[@]}"; do
 				if [ -d "$_resolved_dir/$subdir" ]; then
-					__syz::process_dir load "$subdir" "$_resolved_dir/$subdir"
+					__syz::__process_dir load "$subdir" "$_resolved_dir/$subdir"
 				fi
 			done
 			# remember that this is loaded
@@ -150,7 +150,7 @@ function syz::isloaded {
 	local i
 	local _actually_loaded
 	for i; do
-		if __syz::isloaded "$i" _actually_loaded; then
+		if __syz::__isloaded "$i" _actually_loaded; then
 			echo "$_actually_loaded loaded"
 		else
 			echo "$i not loaded"
@@ -165,7 +165,7 @@ function syz::unload {
 	local _actually_loaded
 	local _resolved_pv _resolved_dir
 	for i; do
-		if ! __syz::isloaded "$i" _actually_loaded; then
+		if ! __syz::__isloaded "$i" _actually_loaded; then
 			echo "syz: Error: No module named $i is loaded"
 			continue
 		fi
@@ -175,7 +175,7 @@ function syz::unload {
 		# not a real/actual module name).
 
 		# FIXME: do not search for the right dir. instead, use the dir from $SYZ_MODULES_ABS
-		if __syz::resolve_loadable_dir "$_actually_loaded" _resolved_pv _resolved_dir; then
+		if __syz::__resolve_loadable_dir "$_actually_loaded" _resolved_pv _resolved_dir; then
 			echo "Unloading $_resolved_pv from $_resolved_dir"
 			# actually unload it
 			# FIXME: this should be a function
@@ -184,14 +184,14 @@ function syz::unload {
 			local subdir
 			for subdir in "${__syz_subdirs[@]}"; do
 				# aggressively try to unload everything, even if the subdir doesn't actually exist anymore.
-				__syz::process_dir unload "$subdir" "$_resolved_dir/$subdir"
+				__syz::__process_dir unload "$subdir" "$_resolved_dir/$subdir"
 			done
 			# forget that this was loaded
 			remove_path SYZ_MODULES "$_resolved_pv"
 			remove_path SYZ_MODULES_ABS "$_resolved_dir"
 		else
 			# YIKES
-			# Module has been loaded, but now fails __syz::is_loadable_dir.
+			# Module has been loaded, but now fails __syz::__is_loadable_dir.
 			# This is an "orphaned" module.
 			# The files have actually been removed from the previous location on disk, oh well, too bad so sad.
 			#
@@ -213,9 +213,9 @@ function syz::avail {
 	local basedir
 	local -a _modules=()
 	local -a _syz_path
-	__syz::parse_list _syz_path "$SYZ_PATH"
+	__syz::__parse_list _syz_path "$SYZ_PATH"
 	if [ "$SYZ_PATH" ]; then
-		__syz::set_nullglob
+		__syz::__set_nullglob
 		for basedir in "${_syz_path[@]}"; do
 			local pkgdir
 			for pkgdir in "$basedir"/*; do
@@ -242,12 +242,12 @@ function syz::avail {
 				for versiondir in "$pkgdir"/*; do
 					local version="${versiondir#$pkgdir/}"
 
-					if __syz::fancy_output; then
+					if __syz::__fancy_output; then
 						if [ "$version" = current -a "$current" ]; then
 							: # ignore
 						elif [ "$version" = default -a "$default" ]; then
 							: # ignore
-						elif __syz::is_loadable_dir "$versiondir"; then
+						elif __syz::__is_loadable_dir "$versiondir"; then
 							local suffix=""
 							if [ "$current" = "$version" ]; then
 								suffix+=" (current)"
@@ -260,18 +260,18 @@ function syz::avail {
 							: # ignore
 						fi
 					else
-						if __syz::is_loadable_dir "$versiondir"; then
+						if __syz::__is_loadable_dir "$versiondir"; then
 							_modules+=("$pkgname/$version")
 						fi
 					fi
 				done
 			done
 		done
-		__syz::restore_nullglob
+		__syz::__restore_nullglob
 	fi
 	local _str
-	__syz::stringify_array -d "$__syz_nl" _str _modules
-	__syz::columnate "Available modules" "No modules available." <<< "$_str"
+	__syz::__stringify_array -d "$__syz_nl" _str _modules
+	__syz::__columnate "Available modules" "No modules available." <<< "$_str"
 }
 
 
@@ -298,23 +298,23 @@ function syz::version {
 
 
 function prepend_path {
-	__syz::adjust_list_var prepend : "$@"
+	__syz::__adjust_list_var prepend : "$@"
 }
 
 
 function append_path {
-	__syz::adjust_list_var append : "$@"
+	__syz::__adjust_list_var append : "$@"
 }
 
 
 function bin_dir {
 	#prepend_path PATH "$@"
 	#FIXME: deal better with $mode
-	__syz::process_dir "$mode" bin "$@"
+	__syz::__process_dir "$mode" bin "$@"
 }
 
 function remove_path {
-	__syz::remove_list_var : "$@"
+	__syz::__remove_list_var : "$@"
 }
 
 
@@ -327,7 +327,7 @@ function remove_path {
 ##################################################
 
 
-function __syz::rerun_if_updated {
+function __syz::__rerun_if_updated {
 	# FIXME: use a hash of the file contents instead
 	local modtime="$(stat -L -c '%Y' "$SYZ_SOURCE")"
 	if [ "$SYZ_SOURCED_AT" -a "$modtime" -a "$modtime" -gt "$SYZ_SOURCED_AT" ]; then
@@ -342,7 +342,7 @@ function __syz::rerun_if_updated {
 }
 
 
-function __syz::process_dir {
+function __syz::__process_dir {
 	local mode="$1" ; shift
 	local type="$1" ; shift
 	case "$mode" in
@@ -380,11 +380,11 @@ function __syz::process_dir {
 }
 
 
-function __syz::isloaded {
+function __syz::__isloaded {
 	local looking_for="$1" ; shift
 	local ${1+-n} found="$1" ; shift
 	local -a _loaded
-	__syz::parse_list _loaded "$SYZ_MODULES"
+	__syz::__parse_list _loaded "$SYZ_MODULES"
 	local i
 	local rc=1
 	for i in "${_loaded[@]}"; do
@@ -400,7 +400,7 @@ function __syz::isloaded {
 }
 
 
-function __syz::resolve_loadable_dir {
+function __syz::__resolve_loadable_dir {
 	# FIXME: if no trailing "/<version>", then figure out and use the default version
 	local target="$1" ; shift
 	local ${1+-n} output_pv="$1" ; shift   # "pv" == "<pkgname>/<version>"
@@ -408,18 +408,18 @@ function __syz::resolve_loadable_dir {
 	local basedir
 	local rc=1
 	local -a _syz_path
-	__syz::parse_list _syz_path "$SYZ_PATH"
+	__syz::__parse_list _syz_path "$SYZ_PATH"
 	if [ "$SYZ_PATH" ]; then
-		__syz::set_nullglob
+		__syz::__set_nullglob
 		for basedir in "${_syz_path[@]}"; do
-			if __syz::is_loadable_dir "$basedir/$target"; then
+			if __syz::__is_loadable_dir "$basedir/$target"; then
 				output_pv="$target"
 				output_dir="$basedir/$target"
 				rc=0
 				break
 			fi
 		done
-		__syz::restore_nullglob
+		__syz::__restore_nullglob
 	fi
 	return "$rc"
 }
@@ -427,29 +427,29 @@ function __syz::resolve_loadable_dir {
 
 declare -a __syz_nullglob_stack
 
-function __syz::set_nullglob {
+function __syz::__set_nullglob {
 	__syz_nullglob_stack+=("$(shopt -p nullglob || true)")
 	shopt -s nullglob
 }
 
 
-function __syz::restore_nullglob {
+function __syz::__restore_nullglob {
 	eval "${__syz_nullglob_stack[${#__syz_nullglob_stack[@]}-1]}"
 	unset __syz_nullglob_stack[${#__syz_nullglob_stack[@]}-1]
 }
 
 
-function __syz::fancy_output {
+function __syz::__fancy_output {
 	# FIXME: allow the user to override
 	# Fancy output for terminals, plain otherwise
 	tty -s 0<&1
 }
 
-function __syz::columnate {
+function __syz::__columnate {
 	local header="$1" ; shift
 	local emptymsg="$1" ; shift
 	local output="$(cat "$@")"
-	if __syz::fancy_output; then
+	if __syz::__fancy_output; then
 		if [ "$output" ]; then
 			if [ "$header" ]; then
 				echo
@@ -480,7 +480,7 @@ function __syz::columnate {
 }
 
 
-function __syz::is_loadable_dir {
+function __syz::__is_loadable_dir {
 	# check for a valid subdir or .syzrc
 	# FIXME: .syzrc in the parent dir is also acceptable
 	if [ -r "$1/.syzrc" ]; then
@@ -496,7 +496,7 @@ function __syz::is_loadable_dir {
 }
 
 
-function __syz::parse_list {
+function __syz::__parse_list {
 	local delim=:
 	if [ x"$1" = x"-d" ]; then
 		delim="$2"
@@ -516,7 +516,7 @@ function __syz::parse_list {
 }
 
 
-function __syz::stringify_array {
+function __syz::__stringify_array {
 	local delim=:
 	if [ x"$1" = x"-d" ]; then
 		delim="$2"
@@ -533,18 +533,18 @@ function __syz::stringify_array {
 }
 
 
-function __syz::absolutify {
+function __syz::__absolutify {
 	echo "$1"
 }
 
 
-function __syz::adjust_list_var {
+function __syz::__adjust_list_var {
 	local type="$1" ; shift
 	local sep="$1" ; shift
 	local var="$1" ; shift
 	local i
 	for i; do
-		i="$(__syz::absolutify "$i")"
+		i="$(__syz::__absolutify "$i")"
 		case "${!var}" in
 			*"$sep$i$sep"*)  ;;  # Already present
 			     "$i$sep"*)  ;;  # Already present
@@ -561,12 +561,12 @@ function __syz::adjust_list_var {
 }
 
 
-function __syz::remove_list_var {
+function __syz::__remove_list_var {
 	local sep="$1" ; shift
 	local var="$1" ; shift
 	local i
 	for i; do
-		i="$(__syz::absolutify "$i")"
+		i="$(__syz::__absolutify "$i")"
 		case "${!var}" in
 			*"$sep$i$sep"*) declare -gx "$var"="${!var/$sep$i$sep/$sep}" ;;
 			     "$i$sep"*) declare -gx "$var"="${!var/#$i$sep}" ;;
